---
apiVersion: v1
kind: Namespace
metadata: 
  name: certmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-Deployment
  namespace: certmanager
  labels:
    app: flask
  spec:
    replicas: 1
